### PR TITLE
chore: onboard APIScan

### PR DESCRIPTION
**Pull request by rzhao271**
This PR modifies the C# packages setup script to allow for a new and separate APIScan pipeline that runs on the internal packages as part of an internal compliance ask. However, with this change, contributors would have to install pwsh and dotnet SDK to set up their workspace.

### CODE REVIEW

**Review by bpasero — COMMENTED** [review]
Can you add a `CONTRIBUTING.md` that explains the setup for a contributor (including myself)?

**Review by bpasero — COMMENTED** [review]
The steps work for me on macOS, but I wonder how we would integrate this into the `vscode-speech` build: currently we run the `preinstall.js` script as part of the NPM install:

https://github.com/microsoft/node-speech/blob/791acd7a1ede1d623634d486c90eb099d4d9ac8a/package.json#L23

Can we run the `pwsh` command here to ensure the install flow remains the same?

**Comment by bpasero** [comment]
cc @joaomoreno

**Review by bpasero — DISMISSED** [review]

**Review by sandy081 — DISMISSED** [review]

**Review by bpasero — APPROVED** [review]

**Comment by bpasero** [comment]
Continues in https://github.com/microsoft/node-speech/pull/41

**Pull request closed without merging**
